language: go
go:
  - master
  - stable
  - "1.14"
  - "1.13"
  - "1.12"
env:
  - GO111MODULE=on
install:
  - go get -t ./...
  - go get github.com/mattn/goveralls
script:
# v1
  - go test -v .
  - go test -v ./exif-read-tool
# v2
  - cd v2
  - go test -v ./...
# v3. Coverage reports comes from this.
  - cd ../v3
  - EXIF_MODULE_ROOT_PATH="$(pwd)" goveralls -v -service=travis-ci
